{
 "title": "Custom exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "city",
    "query": {
     "query": "label_values(weather_temperature_celsius,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Eth price each 3 minutes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "crypto_eth_usd", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Air quality pm2.5 average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(air_pm2_5{city=\"$city\"}[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air quality pm10",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "air_pm10{city=\"$city\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average pressure value for 24 hours on Mars",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "expr": "avg_over_time(mars_pressure_avg[24h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum wind speed on Mars",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(mars_wind_speed_avg[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mars temperature for today",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mars_temperature_avg", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Change rate ETH_USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "rate(crypto_eth_usd[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bitcoin price (USD)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crypto_btc_usd\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Change rate BTC_USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "rate(crypto_btc_usd[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Api status of weather",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_api_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Maximum wind speed for hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "max_over_time(weather_windspeed_kmh{city=\"$city\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Temp 1 hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius{city=\"$city\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}