{
 "title": "Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "database", "label": "database", "query": { "query": "label_values(pg_up,datname)" } }
  ]
 },
 "panels": [
  {
   "title": "Active connections",
   "type": "gauge",
   "description": "Number of active connections in database SphereShop",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"$database\",server=\"host.docker.internal:5433\", state=\"active\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size (bytes)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Rows Fetched (10m)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rows" } },
   "targets": [
    {
     "expr": "avg_over_time(pg_stat_database_tup_fetched{datname=\"$database\"}[10m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{instance=\"my_postgresql_db\", job=\"postgresql\"}) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size (GB)",
   "type": "stat",
   "description": "Current size of the database in gigabytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$database\"} / (1024*1024*1024)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Change Rate (rows/sec)",
   "type": "timeseries",
   "description": "Shows how fast rows are being inserted, updated, and deleted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"$database\"}[5m])\r\n+ rate(pg_stat_database_tup_updated{datname=\"$database\"}[5m])\r\n+ rate(pg_stat_database_tup_deleted{datname=\"$database\"}[5m])\r\n",
     "legendFormat": "{{insert}}"
    }
   ]
  },
  {
   "title": "Read op-s per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"$database\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query processing speed (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"$database\"}[1m])\r\n+\r\nrate(pg_stat_database_xact_rollback{datname=\"$database\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Active Time (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_active_time_seconds_total{datname=\"$database\"}[5m]) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Throughput (rows returned/sec)",
   "type": "timeseries",
   "description": "Shows how many rows PostgreSQL returns per second — reflects overall query volume and activity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}